### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'windup')

### ISSUE THREAD

**Issue by 0ew8fchh** [botkalista/ayaya-league-external#24]
Hi, first, thank you very much for the work you're putting in that project. Please consider adding later a way for users to show their appreciation by donating to you, i would.

The previous versions worked perfectly fine for me but the new version you released today for the 12.6 patch of league of legend is not working at all for me. The software loads and i can see the UI but nothing is enabled in game, not even player's range, etc.

Version : 1.8.4 (Patch 12.16)

This is the error log with the argument "--trace-warnings ..." : 

`ELECTRON 20.0.1 NODE 16.15.0 ARCH ia32
[1408656:0824/191800.452:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[1408656:0824/191800.457:ERROR:disk_cache.cc(203)] Unable to create cache
[1408656:0824/191800.457:ERROR:shader_disk_cache.cc(613)] Shader Cache Creation failed: -2
[1398840:0824/191800.538:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[1398840:0824/191800.538:ERROR:disk_cache.cc(203)] Unable to create cache
(node:1408656) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `AyayaLeague --trace-warnings ...` to show where the warning was created)
AutoSmite.js loaded.
Core.js loaded.
Orbwalker.js loaded.
Loaded 3 user scripts.
ERROR READING NAME AT 797265972
ERROR READING NAME AT 815368948
ERROR READING NAME AT 687182052
ERROR READING NAME AT 711101364
ERROR READING NAME AT 682053988
ERROR READING NAME AT 695296116
(node:1408656) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'windup')
    at getChampionWindup (D:\Softwares\Ay\resources\app\dist\src\utils\Utils.js:9:97)
    at get windupTime [as windupTime] (D:\Softwares\Ay\resources\app\dist\src\models\Entity.js:137:67)
    at Object.onTick (D:\Softwares\Ay\resources\app\scripts\userscripts\Orbwalker.js:48:35)
    at publishToScript (D:\Softwares\Ay\resources\app\dist\src\main\Publisher.js:11:34)
    at publishOnTicks (D:\Softwares\Ay\resources\app\dist\src\events\onTick.js:7:5)
    at Timeout.loop [as _onTimeout] (D:\Softwares\Ay\resources\app\dist\src\main\main.js:113:33)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
(node:1408656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1408656) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'windup')
    at getChampionWindup (D:\Softwares\Ay\resources\app\dist\src\utils\Utils.js:9:97)
    at get windupTime [as windupTime] (D:\Softwares\Ay\resources\app\dist\src\models\Entity.js:137:67)
    at Object.onTick (D:\Softwares\Ay\resources\app\scripts\userscripts\Orbwalker.js:48:35)
    at publishToScript (D:\Softwares\Ay\resources\app\dist\src\main\Publisher.js:11:34)
    at publishOnTicks (D:\Softwares\Ay\resources\app\dist\src\events\onTick.js:7:5)
    at Timeout.loop [as _onTimeout] (D:\Softwares\Ay\resources\app\dist\src\main\main.js:113:33)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
(node:1408656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1408656) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'windup')
    at getChampionWindup (D:\Softwares\Ay\resources\app\dist\src\utils\Utils.js:9:97)
    at get windupTime [as windupTime] (D:\Softwares\Ay\resources\app\dist\src\models\Entity.js:137:67)
    at Object.onTick (D:\Softwares\Ay\resources\app\scripts\userscripts\Orbwalker.js:48:35)
    at publishToScript (D:\Softwares\Ay\resources\app\dist\src\main\Publisher.js:11:34)
    at publishOnTicks (D:\Softwares\Ay\resources\app\dist\src\events\onTick.js:7:5)
    at Timeout.loop [as _onTimeout] (D:\Softwares\Ay\resources\app\dist\src\main\main.js:113:33)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
(node:1408656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:1408656) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'windup')
    at getChampionWindup (D:\Softwares\Ay\resources\app\dist\src\utils\Utils.js:9:97)
    at get windupTime [as windupTime] (D:\Softwares\Ay\resources\app\dist\src\models\Entity.js:137:67)
    at Object.onTick (D:\Softwares\Ay\resources\app\scripts\userscripts\Orbwalker.js:48:35)
    at publishToScript (D:\Softwares\Ay\resources\app\dist\src\main\Publisher.js:11:34)
    at publishOnTicks (D:\Softwares\Ay\resources\app\dist\src\events\onTick.js:7:5)
    at Timeout.loop [as _onTimeout] (D:\Softwares\Ay\resources\app\dist\src\main\main.js:113:33)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
(node:1408656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:1408656) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'windup')
    at getChampionWindup (D:\Softwares\Ay\resources\app\dist\src\utils\Utils.js:9:97)
    at get windupTime [as windupTime] (D:\Softwares\Ay\resources\app\dist\src\models\Entity.js:137:67)
    at Object.onTick (D:\Softwares\Ay\resources\app\scripts\userscripts\Orbwalker.js:48:35)
    at publishToScript (D:\Softwares\Ay\resources\app\dist\src\main\Publisher.js:11:34)
    at publishOnTicks (D:\Softwares\Ay\resources\app\dist\src\events\onTick.js:7:5)
    at Timeout.loop [as _onTimeout] (D:\Softwares\Ay\resources\app\dist\src\main\main.js:113:33)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
(node:1408656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:1408656) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'windup')
    at getChampionWindup (D:\Softwares\Ay\resources\app\dist\src\utils\Utils.js:9:97)
    at get windupTime [as windupTime] (D:\Softwares\Ay\resources\app\dist\src\models\Entity.js:137:67)
    at Object.onTick (D:\Softwares\Ay\resources\app\scripts\userscripts\Orbwalker.js:48:35)
    at publishToScript (D:\Softwares\Ay\resources\app\dist\src\main\Publisher.js:11:34)
    at publishOnTicks (D:\Softwares\Ay\resources\app\dist\src\events\onTick.js:7:5)
    at Timeout.loop [as _onTimeout] (D:\Softwares\Ay\resources\app\dist\src\main\main.js:113:33)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)
(node:1408656) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
ERROR READING NAME AT 571671916
ERROR READING NAME AT 711101364
ERROR READING NAME AT 695296116
ERROR READING NAME AT 848158788
[1419328:0824/192000.688:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is`

Is it because the software cannot properly create cache ? I didn't have that issue before.

**Comment by kecifej** [comment]
did u change offsets?

**Comment by 0ew8fchh** [comment]
Offsets for what ? There was no instruction about changing offsets in the readme. If you're referring to the offsets being different because of the league patch that landed today, it shouldn't be the problem since botkalista updated the software today for that.

**Comment by botkalista** [comment]
i fixed it rightnow, please wait for the next release in minutes and use that
